server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # AUTH / LOGIN
        - id: auth-service
          uri: lb://MS-INTERFACE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # COMMANDES
        - id: commandes-service
          uri: lb://MS-COMMANDES
          predicates:
            - Path=/api/commandes/**
          filters:
            - StripPrefix=1

        # PRODUITS
        - id: produits-service
          uri: lb://MS-PRODUITS
          predicates:
            - Path=/api/produits/**
          filters:
            - StripPrefix=1

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
