server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: commandes-service
          uri: lb://MS-COMMANDES
          predicates:
            - Path=/commandes/**
          filters:
            - StripPrefix=1

        - id: produits-service
          uri: lb://MS-PRODUITS
          predicates:
            - Path=/produits/**
          filters:
            - StripPrefix=1

        - id: interface-service
          uri: lb://MS-INTERFACE
          predicates:
            - Path=/interface/**
          filters:
            - StripPrefix=1

    discovery:
      locator:
        enabled: true  # allows automatic route discovery via Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
