spring:
  application:
    name: ms-interface
  config:
    import: "optional:configserver:http://localhost:8888"  # URL du config server

server:
  port: 8083  # port de ms-interface

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL de Eureka Server

jwt:
  secret: mySecretKey123   # secret pour JWT
  expiration: 3600000      # durée de validité du token en ms

# Config des microservices à appeler via Feign
ms-produits:
  url: http://localhost:8081  # URL de ms-produits

ms-commandes:
  url: http://localhost:8082  # URL de ms-commandes
