server:
  port: 0 # Keeps dynamic port allocation if desired

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_produits_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Pewv44584691
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect